/**
 * FigureCard — displays a chart generated by the analysis pipeline
 * (analysis/output/figures -> webpage/public/figures).
 */
export default function FigureCard({ src, title, purpose, observation, fullWidth }) {
  return (
    <div className={`figure-card ${fullWidth ? 'full-width' : ''}`}>
      <h3>{title}</h3>
      {purpose && <p className="purpose">{purpose}</p>}
      <img src={`/figures/${src}`} alt={title} loading="lazy" />
      {observation && (
        <div className="observation">
          <div className="obs-label">Observation</div>
          {observation}
        </div>
      )}
    </div>
  )
}